
version: '3'

services:
  webssh-dev:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: webssh-dev
    working_dir: /root/code/webssh
    ports:
        - "8889:8888"
    entrypoint:
        - /bin/bash
        - -c
        - python main.py



